# version: '3.8'

services:
  fastapi:
    build: apiserver:latest
    container_name: fastapi-container
    image: fastapi-container
    ports:
      - "8000:8000"
    volumes:
    - .:/app  # 로컬 프로젝트 폴더를 컨테이너와 동기화
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app"]  # 개발 모드에서 코드 변경 시 자동으로 서버 재시작
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      DATABASE_URL: postgresql+asyncpg://myuser:mypassword@db:5432/mydatabase

  db:
    image: postgres:17.3
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydatabase"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: